### PR TITLE
@import-once support - Just for reference

### PR DESCRIPTION
**Pull request by IceReaper**
This pull request is not meant to be merged - as this is not an official scss feature yet.
The reason for this pull request is to make it easier for people to find and use for their own projects.

However if there might be any chance on getting this to merge, feel free to comment and i will do so. Maybe enabling via __construct(boolean $enableUnofficialExtensions); or a way to write extensions to the parser.

### CODE REVIEW

**Comment by robocoder** [comment]
`@importOnce` doesn't follow sass naming convention. `@import-once` might be better. Perhaps `@scssphp-import-once` (if we borrow the idea of vendor prefixes)? I honestly haven't give much thought to how we'd manage unofficial language extensions. There's a lot to consider, for example, would it have to be feature detectable via `feature-exists()`?

**Comment by IceReaper** [comment]
About the naming and prefix suggestion, i agree, that a good point and ill rename that. About the feature-exists: Thats a tricky part as it might be easy to implement if its hardcoded, but possibly a better idea to have some kind of plugin-system.

Thinking about that, a plugin or extension should be able to hook into multiple points to be mighty enough to be called usefull. If however it gives enough flexibility, you might start to think about splitting parts of the parser etc. into build-in extensions so they get modular.

**Comment by robocoder** [comment]
On second thought, don't worry.  I can copy/paste and set the author when committing.

**Comment by IceReaper** [comment]
Btw: any plans on adding such feature?
Since writing this addition, i keep splitting my projects into fragments, each with its own javascript, html and scss files. Every "package" using include-once in the scripts and scss files to make sure their dependencies exists. This way i can come up with a very nice portable and reusable frontend framework. Without the include-once thing, it would add dependencies (bootstrap components for example) multiple times. Its absolutely usefull when it comes to dependency management - so any chance maybe? I would prefer to use the composer version again, instead of manually adding my github fork :D

**Comment by robocoder** [comment]
Still pondering. I understand the pain -- I have a couple of non-standard features that I maintain elsewhere.

**Comment by robocoder** [comment]
This has been merged into master. Thanks.

**Pull request closed without merging**
