### PR TITLE
See #135: add inline sourceMaps support

### PR DESCRIPTION
**Pull request by NicolaF**
* Add setSourceMap() and setSourceMapOptions() methods.
 * Modify Parser, InputBlock and and Block to keep track of the original source file, line and and column.
 * Add SourceMapGenerator, hugely copied from oyekorge/less.php
 * Modify formatters to keep track of the current position, and to call SourceMapGenerator::addMapping when needed.
 * add sourceMap inlining to Compiler

### CODE REVIEW

**Comment by robocoder** [comment]
@oyejorge due to the license difference, can we get your permission to copy and relicense the derivative code for use in this project?

**Comment by robocoder** [comment]
ping @oyejorge

**Comment by WhatCMSAdmin** [comment]
That's perfectly ok with me. Sorry for the delayed response

**Comment by oyejorge** [comment]
That's perfectly OK with me, sorry for the delayed response

**Comment by robocoder** [comment]
@NicolaF and @oyejorge : thank you!

**Comment by kevindoveton** [comment]
@NicolaF @robocoder i've had a few issues with this - it worked perfectly fine with one site but in the second site 90% of my classes are showing as either the first line or the last line of the main file

**Comment by NicolaF** [comment]
@robocoder You're welcome!
@kevindoveton I need more details to help you.

- Which formatter do you use?
- Which options (`sourceMapPath`/`sourceMapURL`).
- Can you check the generated source map to see where it starts getting wrong ?

To grab the source map,add a `file_put_contents('/tmp.sourcemap.json,$sourceMap)` in Compiler.php after line 209. To parse the source map, you can use the attached node script : `node test.js /tmp/sourcemap.json`.
[sourceMapTest.zip](https://github.com/leafo/scssphp/files/1562154/sourceMapTest.zip)

**Pull request merged**
