### PR TITLE
integrated optional line numbering functionality

### PR DESCRIPTION
**Pull request by gerhard-boden**
output the original SCSS line numbers within the compiled CSS file for better frontend debugging.

works great in combination with frontend debugging tools like https://addons.mozilla.org/de/firefox/addon/firecompass-for-firebug/

to activate this feature you need to call ->setLineNumbers(true) after creating a new instance of compiler.php

For full description see:
https://github.com/Screenchecker/scssphp/tree/develop#optional-output-scss-line-numbers

### CODE REVIEW

**Comment by robocoder** [comment]
It seems you weren't able to rebase and squash, so I opted to instead cherry-pick 2aab9e7 into the `line-numbers-v2` branch as it seemed to have fewer merge conflicts for me to resolve.

https://github.com/leafo/scssphp/tree/line-numbers-v2

I'll finish reviewing the PR this week.

**Comment by gerhard-boden** [comment]
that's odd, git reported "successfully rebased and updated" without any conflict or error. 
if you still need the squashed commits just say so and ill look into it again.

the cherry pick strategy seems to be a good call, since there were only very minor changes since the first version of the "line-numbers" branch last week. tests need to be rebuild of course, since the output will be different now.

**Comment by robocoder** [comment]
Seems to still have some edge cases, such as unexpected and/or missing line comments, e.g.,
* https://github.com/leafo/scssphp/blob/line-numbers-v2/tests/outputs_numbered/compass_extract.css
* https://github.com/leafo/scssphp/blob/line-numbers-v2/tests/outputs_numbered/comments.css

Instead of the extra pass, maybe we could add hints to the Parser. I created an `experiment-line-numbers` branch to rough out this idea but it isn't without its own set of challenges:
* line numbers are off
* formatting: Nested adds an extra newline, while Expanded should add a newline
* extra line comments with imports/partials

**Comment by gerhard-boden** [comment]
The extra pass is indeed not the perfect solution. When I wrote the basic first version in a couple of hours  I tried to interfere with the core scssphp parser as little as possible since I was looking for  a quick solution. It's a more modular approach. 

Like I said above the line comment output might not always be perfect, but in 99% of the real life cases the overhead is very low and the firebug debugger extension will get it right. Some scss input used for the test cases can't be described as realistic code (which is deliberate to cover a lot of scenarios of course).

Nonetheless, I welcome the new approach to integrate the line number functionality directly into the parser and I'm very happy to help. This would also be a great chance to integrate sourcemaps, since the basic approach would be the same. Or should we drop line numbers completely in favour of sourcemaps  which would be a more elegant debugging solution?

**Comment by robocoder** [comment]
Both approaches have their +/-.  I agree this will probably set the stage for source maps. Let's tinker with this a bit.

**Comment by gerhard-boden** [comment]
will the `line-numbers-v2` branch stay a development branch in the meantime or will it still be merged into into the master branch until a better solution becomes available? Some people have been waiting for official debugging support for quite some time now and I think it would be a  pity they would have to wait again just because of minor flaws.

Or will `line-numbers-v2` still receive the latest updates like the master branch?

**Comment by robocoder** [comment]
I'm going to keep both branches updated until a decision is made on which to mainline. I've started looking at source maps support, so that will weigh in.

**Comment by gerhard-boden** [comment]
That is awesome! I think it's worth mentioning that the line number branches will still receive the latest updates here: https://github.com/leafo/scssphp/issues/88#issuecomment-111465417 

So people know that they can use it without having to use an older version of scssphp.

Source maps: 
I already looked into it a couple of months ago, but i ran out of time. 
I'm looking at my old code right now ... it was just a prototype approach (at best). 
I used line numbered CSS output to generate a basic map output (not even in a separate file yet, but just as a JSON string for testing). So this approach would even require a second pass (not what we want)n

But i guess it will be tricky knowing the exact line number for the final CSS file while parsing trough the SCSS code. Especially includes and functions will make things interesting.

**Pull request closed without merging**
