### PR TITLE
Various fixes to closer match Sass 3.5

### PR DESCRIPTION
**Pull request by niaccurshi**
Having sync'd with the master branch that I seem to have got away from somehow, the changes are now in place to fix some issues and add functionality to SCSSPHP to more closely match how it should run as 3.5.

### CODE REVIEW

**Comment by robocoder** [comment]
It doesn't look like you rebased. bdb776e8 and 6f4b1212 were causing a merge conflict when I looked at this PR this morning.

**Comment by robocoder** [comment]
I checked out your branch and there are numerous failing unit tests. Some of these might be ok due to the scope changes you added, but some clearly introduced a regression, e.g.,

```
-  cancel-unit: 1; }
+  cancel-unit: 10px / 10px; }
```
and
```
-:not([foo^="bar"]) {
+:not([foo^=) {
```

**Comment by robocoder** [comment]
Rebasing with master from `leafo/scssphp` didn't fix the unit tests (but it did clean up the commit history).

**Comment by niaccurshi** [comment]
Sure, I'm not sure how those regressions are in there, I guess these improvements will just have to stagnate for a while until I find some time in the future to revisit this topic. Shame.

**Pull request closed without merging**
