### PR TITLE
integrated optional line numbering functionality

### PR DESCRIPTION
**Pull request by gerhard-boden**
output the original SCSS line numbers within the compiled CSS file for better frontend debugging.

works great in combination with frontend debugging tools like https://addons.mozilla.org/de/firefox/addon/firecompass-for-firebug/

to activate this feature you need to call ->setLineNumbers(true) after creating a new instance of compiler.php

For full description see:
https://github.com/Screenchecker/scssphp/tree/develop#optional-output-scss-line-numbers

### CODE REVIEW

**Comment by handyface** [comment]
Looks good! However this doesn't seem to work with imported scss files.

**Comment by gerhard-boden** [comment]
thanks a lot for this important bug report!
included scss files will now be considered for line numbering

**Comment by handyface** [comment]
Great! I'll try it out right away.

**Comment by handyface** [comment]
Works like a charm, thanks a lot!

**Comment by gerhard-boden** [comment]
happy to hear that. 
my pleasure!

**Comment by emcniece** [comment]
When is this getting merged?? Do want...

**Comment by robocoder** [comment]
Thanks! Apologies for not getting around to merging this sooner.  I squashed and merged your PR into the `develop` branch.

**Comment by robocoder** [comment]
This isn't quite working the way I expect it, so I've moved it to a new branch.

**Comment by robocoder** [comment]
1. There's a difference in the generated files between those created by```BUILD=true vendor/bin/phpunit``` vs. manually running ```bin/pscss --line-numbers tests/input/some.scss```

Example:
```
/* line 12, map.scss */
div {
  color: black;
  /* line 14, map.scss */
  color: red;
  foo: black, red, #0f0;
  bar: color, length;
  baz: (color: #fff, color2: red, color3: #0f0, length: 40em);
  foo: (length: 40em);
  bar: true; }
/* line 23, map.scss */
div {
  foo: color black;
  bar: color; }
```
vs
```
/* line 12, map.scss */
div {
  color: black;
  color: red;
  foo: black, red, #0f0;
  bar: color, length;
  baz: (color: #fff, color2: red, color3: #0f0, length: 40em);
  foo: (length: 40em);
  bar: true; }

/* line 14, map.scss */
/* line 23, map.scss */
div {
  foo: color black;
  bar: color; }
```

2. The annotation is only expected before selectors. But in the example above, there's an unexpected "line 14, map.scss".

**Comment by gerhard-boden** [comment]
Hi @robocoder! 

Thanks a lot for your feedback and for the branch!

I've made three changes here: https://github.com/gerhard-boden/scssphp

1. test cases now produce exactly the same output like CLI commands or any other call
2. the curly braces used in map_get for selecting a value by index are now no longer confused as a declartion block.
3. line number comments are now never placed within declaration blocks (that also goes for test cases). In some (rare) cases multiple line comments will be placed underneath each other after certain blocks, but this won't hurt debugging (since the last one will aways belong to the next selector underneath it). The rule is for this debugging extension is: better too much than too little

Furthermore this will most likely be used in "debugging" modes and not in live production and for that reason alone the (in some rare cases) produced overhead descriped number 3 is negligible.

Any chance that you could merge the "line-numbers" branch into the "develop" branch?

Should i create a new pull request for it?

**Comment by robocoder** [comment]
OK. Rebase and squash your commits, and submit a new PR.

**Comment by gerhard-boden** [comment]
alright! Should i submit the PR to the new line-numbers branch or the develop branch?

**Comment by robocoder** [comment]
master; the line-numbers branch is obsolete; the develop branch was nuked in favour of develop branches

**Comment by gerhard-boden** [comment]
done, rebased and squashed all 30 commits. new PR is out.

**Pull request closed without merging**
