### PR TITLE
some protect to private for open extends

### PR DESCRIPTION
**Pull request by surikat**
Hello, I need some methods and properties to be protected instead of private, so I can extends Compiler class to make my own (with PHP support in SCSS, and some autoloaders for mixin, fonts etc...)

### CODE REVIEW

**Comment by mahagr** [comment]
I agree on opening up these functions; I have my own php streams based loader with support for overrides and I'm currently hacking around these functions.

**Comment by robocoder** [comment]
Deferring. There are numerous scope compatibility issues that need to be resolved and could entail significant changes to Compiler's `env`, `storeEnv`, and `scope` properties.

**Comment by mahagr** [comment]
What I do, is to check out the changes for every release and make sure my code doesn't break on composer update. If composer is used in a correct way

    composer install --no-dev

It always uses the versions from composer lock file and not the latest version. That allows me to make sure that there's proper checks and testing after every composer update.

**Comment by robocoder** [comment]
This has been cherry-picked.

**Comment by surikat** [comment]
Thank you very much

**Comment by mahagr** [comment]
thanks a lot!

**Pull request closed without merging**
