### PR TITLE
Multiple Optimizations To Speed Up Parser

### PR DESCRIPTION
**Pull request by oyejorge**
These changes primarily reduce the number of function calls when parsing scss.

On my system, compiling bootstrap went from taking over 5 seconds to around 2 seconds.

### CODE REVIEW

**Comment by robocoder** [comment]
Thanks. I'll starting cherry-picking when the holidays are over.

I disagree with some of the changes and there are far too many PSR2 violations to simply merge this PR in its entirety.

**Comment by oyejorge** [comment]
Sounds good. Sorry for submitting such a large pull request, I just kept finding ways to make it faster... though I can understand why you might not like some of them.

**Comment by smachi** [comment]
+1 for merging this. 
Performance is the worst thing of scssphp compiler, so any improvement in this direction is well received.

**Comment by nxtpl** [comment]
yeah please merge as much as possible as the current performance is really bad

**Comment by djcvijic** [comment]
+1 for merge!

**Comment by qzminski** [comment]
Hey, sorry for digging up this issue but what's the status on this? How many of the proposed improvements have been implemented in the latest versions of the compiler?

**Comment by nxtpl** [comment]
Any update?

**Comment by Cerdic** [comment]
I updated a great part of this PR in https://github.com/leafo/scssphp/pull/640 which is safe to be pulled (test OK and PSR2)

**Comment by robocoder** [comment]
Superceded by #640

**Pull request closed without merging**
