### PR TITLE
Resolve function arguments using mixin content scope

### PR DESCRIPTION
**Pull request by FMCorz**
This should resolve (or help resolve) #449, #446.

### CODE REVIEW

**Comment by axi** [comment]
Hi,
should this be used in production?
It fixed bootstrap v4.0.0@3 compilation for me but can't figure out if there is more to do?

**Comment by FMCorz** [comment]
Hi @axi, we, @moodleHQ, will be using it in production soon.

**Comment by axi** [comment]
@FMCorz thanks

**Comment by IceReaper** [comment]
Works flawless :)

**Pull request merged**
