### PR TITLE
Cache system for parser and compiler

### PR DESCRIPTION
**Pull request by Cerdic**
That allows refresh of output if any file change (only parsing changed files and recompiling the whole) and ultra fast compile() if nothing changed

### CODE REVIEW

**Comment by Cerdic** [comment]
NB: there is an update of my maintenance branch https://github.com/Cerdic/scssphp/tree/maint/leafo/master :
* https://github.com/Cerdic/scssphp/commit/c93c83569ce359212318e61956ab3fa0402355da
* https://github.com/Cerdic/scssphp/commit/5e0895fa8ef64e037fb09ace5d57e759ad9750b7
* https://github.com/Cerdic/scssphp/commit/c5479c85201f39dbc97a241b36f84e58a003e67c

which is directly usable on top of all other PRs, and where I fixed all PSR2 coding rules

**Comment by robocoder** [comment]
Hi @Cerdic . Thanks for all the time & effort you're putting into updating the PRs.

I'm going to defer merging this one for the moment as it overlaps with some of the refactoring that I've been pondering for #333.

**Comment by Cerdic** [comment]
OMG! I never opened the `example/` folders and was really wondering what this `Server` class was about and if it moved in a separate project or anything else… :D

OK, so now I can see that this need some additional work for a coherent thing

(But as I'm not using the Server Class at all, not sure to have time to look on that in a near future, even if interresting because then avoiding me to keep a special branch on my repo for getting this feature working)

**Comment by robocoder** [comment]
I'll try to get some traction on this so you don't have to maintain this branch separately.

**Comment by Cerdic** [comment]
Then I will send an update with what I have on my repo: some small things and an extension of the force_refresh flag to refresh only once each cache in a hit. 

That allows to get an effective forced refresh without re-parsing multiple times same mixins source if you are compiling several files in a row.

**Comment by Cerdic** [comment]
to be continued in #678

**Pull request closed without merging**
